[package]
name = "grpc-calculator"
version = "0.1.0"
edition = "2021"

[dependencies]
tonic = "0.12.1"
tokio = { version = "1.0", features = ["rt-multi-thread", "macros"] }
prost = "0.13.1"

[build-dependencies]
tonic-build = "0.12.1"

[[bin]]
name = "server"
path = "src/server.rs"
